//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandsClothes
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateHistory
    {
        public int ID { get; set; }
        public int Material { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int NewCount { get; set; }
    
        public virtual Material Material1 { get; set; }
    }
}
